from fabric.api import local

local_absolute_path = '/Users/Tom/projects/land-records/repo/scripts/'
server_absolute_path = '/apps/land-records/repo/scripts'
s3_path = 's3://lensnola/land-records-temp/'

def deploy():
    local("./deploy.sh")

def app_config():
    local('scp %sapp_config.py          tom@162.243.152.217:%s' % (local_absolute_path, server_absolute_path))

def holytrinity():
    local('scp %sdatabasedeleter.py     tom@162.243.152.217:%s' % (local_absolute_path, server_absolute_path))
    local('scp %sdatabasemaker.py       tom@162.243.152.217:%s' % (local_absolute_path, server_absolute_path))
    local('scp %sinitialize.py          tom@162.243.152.217:%s' % (local_absolute_path, server_absolute_path))

def staticfiles():
    local('scp %sstatic/css/lens.css    tom@162.243.152.217:%s/static/css' % (local_absolute_path, server_absolute_path))
    local('scp %sstatic/js/dashboard.js tom@162.243.152.217:%s/static/js' % (local_absolute_path, server_absolute_path))
    local('scp %sstatic/js/index.js     tom@162.243.152.217:%s/static/js' % (local_absolute_path, server_absolute_path))
    local('scp %sstatic/js/sale.js      tom@162.243.152.217:%s/static/js' % (local_absolute_path, server_absolute_path))
    local('scp %sstatic/js/search.js    tom@162.243.152.217:%s/static/js' % (local_absolute_path, server_absolute_path))

    local('scp %stemplates/dashboard.html   tom@162.243.152.217:%s/templates' % (local_absolute_path, server_absolute_path))
    local('scp %stemplates/index.html       tom@162.243.152.217:%s/templates' % (local_absolute_path, server_absolute_path))
    local('scp %stemplates/sale.html        tom@162.243.152.217:%s/templates' % (local_absolute_path, server_absolute_path))
    local('scp %stemplates/search.html      tom@162.243.152.217:%s/templates' % (local_absolute_path, server_absolute_path))
    local('scp %stemplates/table.html       tom@162.243.152.217:%s/templates' % (local_absolute_path, server_absolute_path))

    local('aws s3 cp %sstatic/css/lens.css                        %scss/lens.css --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/js/dashboard.js                     %sjs/dashboard.js --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/js/sale.js                          %sjs/sale.js --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/js/search.js                        %sjs/search.js --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/js/index.js                         %sjs/index.js --acl public-read' % (local_absolute_path, s3_path))

def s3():
    local('aws s3 cp %sstatic/css/font-awesome.css                %scss/font-awesome.css --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/css/foundation.css                  %scss/foundation.css --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/css/foundation.min.css              %scss/foundation.min.css --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/css/jquery-ui-1.9.2.custom.css      %scss/jquery-ui-1.9.2.custom.css --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/css/jquery-ui.css                   %scss/jquery-ui.css --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/css/jquery.tablesorter.pager.css    %scss/jquery.tablesorter.pager.css --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/css/lens.css                        %scss/lens.css --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/css/lenstablesorter.css             %scss/lenstablesorter.css --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/css/mapbox.css                      %scss/mapbox.css --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/css/tablesorter.css                 %scss/tablesorter.css --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/css/theme.blue.css                  %scss/theme.blue.css --acl public-read' % (local_absolute_path, s3_path))

    local('aws s3 cp %sstatic/css/images/ajax-loader.gif                  %scss/images/ajax-loader.gif --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/css/images/black-asc.gif                    %scss/images/black-asc.gif --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/css/images/black-desc.gif                   %scss/images/black-desc.gif --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/css/images/black-unsorted.gif               %scss/images/black-unsorted.gif --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/css/images/favicon.ico                      %scss/images/favicon.ico --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/css/images/first.png                        %scss/images/first.png --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/css/images/icons-000000.png                 %scss/images/icons-000000.png --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/css/images/icons-000000@2x.png              %scss/images/icons-000000@2px.png --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/css/images/info-i.png                       %scss/images/info-i.png --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/css/images/last.png                         %scss/images/last.png --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/css/images/lens-info.png                    %scss/images/lens-info.png --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/css/images/lens-logo.png                    %scss/images/lens-logo.png --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/css/images/next.png                         %scss/images/next.png --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/css/images/prev.png                         %scss/images/prev.png --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/css/images/ui-bg_flat_75_ffffff_40x100.png  %scss/images/ui-bg_flat_75_ffffff_40x100.png --acl public-read' % (local_absolute_path, s3_path))

    local('aws s3 cp %sstatic/fonts/fontawesome-webfont.eot   %sfonts/fontawesome-webfont.eot --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/fonts/fontawesome-webfont.svg   %sfonts/fontawesome-webfont.svg --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/fonts/fontawesome-webfont.ttf   %sfonts/fontawesome-webfont.ttf --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/fonts/fontawesome-webfont.woff  %sfonts/fontawesome-webfont.woff --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/fonts/FontAwesome.otf           %sfonts/FontAwesome.otf --acl public-read' % (local_absolute_path, s3_path))

    local('aws s3 cp %sstatic/js/dashboard.js                     %sjs/dashboard.js --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/js/foundation.min.js                %sjs/foundation.min.js --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/js/foundation.tooltip.js            %sjs/foundation.tooltip.js --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/js/index.js                         %sjs/index.js --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/js/jquery-1.11.0.min.js             %sjs/jquery-1.11.0.min.js --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/js/jquery-ui.js                     %sjs/jquery-ui.js --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/js/jquery.tablesorter.min.js        %sjs/jquery.tablesorter.min.js --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/js/jquery.tablesorter.pager.min.js  %sjs/jquery.tablesorter.pager.min.js --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/js/leaflet.js                       %sjs/leaflet.js --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/js/lens.js                          %sjs/lens.js --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/js/mapbox.uncompressed.js           %sjs/mapbox.uncompressed.js --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/js/modernizr.js                     %sjs/modernizr.js --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/js/neighborhoods-topo.js            %sjs/neighborhoods-topo.js --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/js/neighborhoods-topo.min.js        %sjs/neighborhoods-topo.min.js --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/js/sale.js                          %sjs/sale.js --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/js/search.js                        %sjs/search.js --acl public-read' % (local_absolute_path, s3_path))
    local('aws s3 cp %sstatic/js/squares-topo.js                  %sjs/squares-topo.js --acl public-read' % (local_absolute_path, s3_path))

def essentials():
    local('scp %sapp.py                 tom@162.243.152.217:%s' % (local_absolute_path, server_absolute_path))
    #local('scp %sapp_config.py          tom@162.243.152.217:%s' % (local_absolute_path, server_absolute_path))
    local('scp %scheck_assessor_urls.py tom@162.243.152.217:%s' % (local_absolute_path, server_absolute_path))
    local('scp %sCleanup.py             tom@162.243.152.217:%s' % (local_absolute_path, server_absolute_path))
    local('scp %sdatabasedeleter.py     tom@162.243.152.217:%s' % (local_absolute_path, server_absolute_path))
    local('scp %sdatabasemaker.py       tom@162.243.152.217:%s' % (local_absolute_path, server_absolute_path))
    local('scp %sfabfile.py             tom@162.243.152.217:%s' % (local_absolute_path, server_absolute_path))
    local('scp %sgmail.py               tom@162.243.152.217:%s' % (local_absolute_path, server_absolute_path))
    local('scp %sinitialize.py          tom@162.243.152.217:%s' % (local_absolute_path, server_absolute_path))
    local('scp %sscreen.js              tom@162.243.152.217:%s' % (local_absolute_path, server_absolute_path))
    local('scp %stwitter.py             tom@162.243.152.217:%s' % (local_absolute_path, server_absolute_path))

def templates():
    local('scp %stemplates/dashboard.html   tom@162.243.152.217:%s/templates' % (local_absolute_path, server_absolute_path))
    local('scp %stemplates/index.html       tom@162.243.152.217:%s/templates' % (local_absolute_path, server_absolute_path))
    local('scp %stemplates/sale.html        tom@162.243.152.217:%s/templates' % (local_absolute_path, server_absolute_path))
    local('scp %stemplates/search.html      tom@162.243.152.217:%s/templates' % (local_absolute_path, server_absolute_path))
    local('scp %stemplates/table.html       tom@162.243.152.217:%s/templates' % (local_absolute_path, server_absolute_path))

def alltoserver():
    local('scp %sapp.py                 tom@162.243.152.217:%s' % (local_absolute_path, server_absolute_path))
    # #local('scp %sapp_config.py          tom@162.243.152.217:%s' % (local_absolute_path, server_absolute_path))
    # local('scp %sbuild_assessor_urls.py tom@162.243.152.217:%s' % (local_absolute_path, server_absolute_path))
    # local('scp %sCleanup.py             tom@162.243.152.217:%s' % (local_absolute_path, server_absolute_path))
    # local('scp %sdatabasedeleter.py     tom@162.243.152.217:%s' % (local_absolute_path, server_absolute_path))
    # local('scp %sdatabasemaker.py       tom@162.243.152.217:%s' % (local_absolute_path, server_absolute_path))
    # local('scp %sfabfile.py             tom@162.243.152.217:%s' % (local_absolute_path, server_absolute_path))
    # local('scp %sgeocoder-commands.txt  tom@162.243.152.217:%s' % (local_absolute_path, server_absolute_path))
    # local('scp %sgmail.py               tom@162.243.152.217:%s' % (local_absolute_path, server_absolute_path))
    # local('scp %sinitialize.py          tom@162.243.152.217:%s' % (local_absolute_path, server_absolute_path))
    # local('scp %skey.json          tom@162.243.152.217:%s' % (local_absolute_path, server_absolute_path))
    # local('scp %sneighborhoods-topo.json tom@162.243.152.217:%s' % (local_absolute_path, server_absolute_path))
    # local('scp %sneighborhoods.json     tom@162.243.152.217:%s' % (local_absolute_path, server_absolute_path))
    # local('scp %sphantomjs              tom@162.243.152.217:%s' % (local_absolute_path, server_absolute_path))
    # local('scp %srequirements.txt       tom@162.243.152.217:%s' % (local_absolute_path, server_absolute_path))
    # local('scp %sscrape.sh              tom@162.243.152.217:%s' % (local_absolute_path, server_absolute_path))
    # local('scp %sscrape.py              tom@162.243.152.217:%s' % (local_absolute_path, server_absolute_path))
    # local('scp %sscreen.js              tom@162.243.152.217:%s' % (local_absolute_path, server_absolute_path))
    # local('scp %ssquares-topo.json      tom@162.243.152.217:%s' % (local_absolute_path, server_absolute_path))
    # local('scp %ssquares.json           tom@162.243.152.217:%s' % (local_absolute_path, server_absolute_path))
    # local('scp %stserver.py             tom@162.243.152.217:%s' % (local_absolute_path, server_absolute_path))
    # local('scp %stwitter.py             tom@162.243.152.217:%s' % (local_absolute_path, server_absolute_path))
    # local('scp %s.gitignore             tom@162.243.152.217:%s' % (local_absolute_path, server_absolute_path))

    # local('scp /Users/Tom/projects/land-records/repo/data/neighborhoods/102682.prj tom@162.243.152.217:/apps/land-records/repo/data/neighborhoods')
    # local('scp /Users/Tom/projects/land-records/repo/data/neighborhoods/Neighborhood_Statistical_Areas.dbf tom@162.243.152.217:/apps/land-records/repo/data/neighborhoods')
    # local('scp /Users/Tom/projects/land-records/repo/data/neighborhoods/Neighborhood_Statistical_Areas.json tom@162.243.152.217:/apps/land-records/repo/data/neighborhoods')
    # local('scp /Users/Tom/projects/land-records/repo/data/neighborhoods/Neighborhood_Statistical_Areas.prj tom@162.243.152.217:/apps/land-records/repo/data/neighborhoods')
    # local('scp /Users/Tom/projects/land-records/repo/data/neighborhoods/Neighborhood_Statistical_Areas.sbn tom@162.243.152.217:/apps/land-records/repo/data/neighborhoods')
    # local('scp /Users/Tom/projects/land-records/repo/data/neighborhoods/Neighborhood_Statistical_Areas.sbx tom@162.243.152.217:/apps/land-records/repo/data/neighborhoods')
    # local('scp /Users/Tom/projects/land-records/repo/data/neighborhoods/Neighborhood_Statistical_Areas.shp tom@162.243.152.217:/apps/land-records/repo/data/neighborhoods')
    # local('scp /Users/Tom/projects/land-records/repo/data/neighborhoods/Neighborhood_Statistical_Areas.shp.xml tom@162.243.152.217:/apps/land-records/repo/data/neighborhoods')
    # local('scp /Users/Tom/projects/land-records/repo/data/neighborhoods/Neighborhood_Statistical_Areas.shx tom@162.243.152.217:/apps/land-records/repo/data/neighborhoods')

    # local('scp /Users/Tom/projects/land-records/repo/data/squares/102682.prj tom@162.243.152.217:/apps/land-records/repo/data/squares')
    # local('scp /Users/Tom/projects/land-records/repo/data/squares/NOLA_Squares_20140221.dbf tom@162.243.152.217:/apps/land-records/repo/data/squares')
    # local('scp /Users/Tom/projects/land-records/repo/data/squares/NOLA_Squares_20140221.prj tom@162.243.152.217:/apps/land-records/repo/data/squares')
    # local('scp /Users/Tom/projects/land-records/repo/data/squares/NOLA_Squares_20140221.sbn tom@162.243.152.217:/apps/land-records/repo/data/squares')
    # local('scp /Users/Tom/projects/land-records/repo/data/squares/NOLA_Squares_20140221.sbx tom@162.243.152.217:/apps/land-records/repo/data/squares')
    # local('scp /Users/Tom/projects/land-records/repo/data/squares/NOLA_Squares_20140221.shp tom@162.243.152.217:/apps/land-records/repo/data/squares')
    # local('scp /Users/Tom/projects/land-records/repo/data/squares/NOLA_Squares_20140221.shp.xml tom@162.243.152.217:/apps/land-records/repo/data/squares')
    # local('scp /Users/Tom/projects/land-records/repo/data/squares/NOLA_Squares_20140221.shx tom@162.243.152.217:/apps/land-records/repo/data/squares')

    # local('scp %stemplates/dashboard.html   tom@162.243.152.217:%s/templates' % (local_absolute_path, server_absolute_path))
    # local('scp %stemplates/index.html       tom@162.243.152.217:%s/templates' % (local_absolute_path, server_absolute_path))
    # local('scp %stemplates/sale.html        tom@162.243.152.217:%s/templates' % (local_absolute_path, server_absolute_path))
    # local('scp %stemplates/search.html      tom@162.243.152.217:%s/templates' % (local_absolute_path, server_absolute_path))
    # local('scp %stemplates/table.html       tom@162.243.152.217:%s/templates' % (local_absolute_path, server_absolute_path))

    # local('scp %sstatic/css/font-awesome.css                tom@162.243.152.217:%s/static/css' % (local_absolute_path, server_absolute_path))
    # local('scp %sstatic/css/foundation.css                  tom@162.243.152.217:%s/static/css' % (local_absolute_path, server_absolute_path))
    # local('scp %sstatic/css/foundation.min.css              tom@162.243.152.217:%s/static/css' % (local_absolute_path, server_absolute_path))
    # local('scp %sstatic/css/jquery-ui-1.9.2.custom.css      tom@162.243.152.217:%s/static/css' % (local_absolute_path, server_absolute_path))
    # local('scp %sstatic/css/jquery-ui.css                   tom@162.243.152.217:%s/static/css' % (local_absolute_path, server_absolute_path))
    # local('scp %sstatic/css/jquery.tablesorter.pager.css    tom@162.243.152.217:%s/static/css' % (local_absolute_path, server_absolute_path))
    # local('scp %sstatic/css/lens.css                        tom@162.243.152.217:%s/static/css' % (local_absolute_path, server_absolute_path))
    # local('scp %sstatic/css/lenstablesorter.css             tom@162.243.152.217:%s/static/css' % (local_absolute_path, server_absolute_path))
    # local('scp %sstatic/css/mapbox.css                      tom@162.243.152.217:%s/static/css' % (local_absolute_path, server_absolute_path))
    # local('scp %sstatic/css/tablesorter.css                 tom@162.243.152.217:%s/static/css' % (local_absolute_path, server_absolute_path))
    # local('scp %sstatic/css/theme.blue.css                  tom@162.243.152.217:%s/static/css' % (local_absolute_path, server_absolute_path))

    # local('scp %sstatic/css/images/ajax-loader.gif                  tom@162.243.152.217:%s/static/css/images' % (local_absolute_path, server_absolute_path))
    # local('scp %sstatic/css/images/black-asc.gif                    tom@162.243.152.217:%s/static/css/images' % (local_absolute_path, server_absolute_path))
    # local('scp %sstatic/css/images/black-desc.gif                   tom@162.243.152.217:%s/static/css/images' % (local_absolute_path, server_absolute_path))
    # local('scp %sstatic/css/images/black-unsorted.gif               tom@162.243.152.217:%s/static/css/images' % (local_absolute_path, server_absolute_path))
    # local('scp %sstatic/css/images/favicon.ico                      tom@162.243.152.217:%s/static/css/images' % (local_absolute_path, server_absolute_path))
    # local('scp %sstatic/css/images/first.png                        tom@162.243.152.217:%s/static/css/images' % (local_absolute_path, server_absolute_path))
    # local('scp %sstatic/css/images/icons-000000.png                 tom@162.243.152.217:%s/static/css/images' % (local_absolute_path, server_absolute_path))
    # local('scp %sstatic/css/images/icons-000000@2x.png              tom@162.243.152.217:%s/static/css/images' % (local_absolute_path, server_absolute_path))
    # local('scp %sstatic/css/images/info-i.png                       tom@162.243.152.217:%s/static/css/images' % (local_absolute_path, server_absolute_path))
    # local('scp %sstatic/css/images/last.png                         tom@162.243.152.217:%s/static/css/images' % (local_absolute_path, server_absolute_path))
    # local('scp %sstatic/css/images/lens-info.png                    tom@162.243.152.217:%s/static/css/images' % (local_absolute_path, server_absolute_path))
    # local('scp %sstatic/css/images/lens-logo.png                    tom@162.243.152.217:%s/static/css/images' % (local_absolute_path, server_absolute_path))
    # local('scp %sstatic/css/images/next.png                         tom@162.243.152.217:%s/static/css/images' % (local_absolute_path, server_absolute_path))
    # local('scp %sstatic/css/images/prev.png                         tom@162.243.152.217:%s/static/css/images' % (local_absolute_path, server_absolute_path))
    # local('scp %sstatic/css/images/ui-bg_flat_75_ffffff_40x100.png  tom@162.243.152.217:%s/static/css/images' % (local_absolute_path, server_absolute_path))

    # local('scp %sstatic/fonts/fontawesome-webfont.eot   tom@162.243.152.217:%s/static/fonts' % (local_absolute_path, server_absolute_path))
    # local('scp %sstatic/fonts/fontawesome-webfont.svg   tom@162.243.152.217:%s/static/fonts' % (local_absolute_path, server_absolute_path))
    # local('scp %sstatic/fonts/fontawesome-webfont.ttf   tom@162.243.152.217:%s/static/fonts' % (local_absolute_path, server_absolute_path))
    # local('scp %sstatic/fonts/fontawesome-webfont.woff  tom@162.243.152.217:%s/static/fonts' % (local_absolute_path, server_absolute_path))
    # local('scp %sstatic/fonts/FontAwesome.otf           tom@162.243.152.217:%s/static/fonts' % (local_absolute_path, server_absolute_path))

    # local('scp %sstatic/js/dashboard.js                     tom@162.243.152.217:%s/static/js' % (local_absolute_path, server_absolute_path))
    # local('scp %sstatic/js/foundation.min.js                tom@162.243.152.217:%s/static/js' % (local_absolute_path, server_absolute_path))
    # local('scp %sstatic/js/foundation.tooltip.js            tom@162.243.152.217:%s/static/js' % (local_absolute_path, server_absolute_path))
    # local('scp %sstatic/js/index.js                         tom@162.243.152.217:%s/static/js' % (local_absolute_path, server_absolute_path))
    # local('scp %sstatic/js/jquery-1.11.0.min.js             tom@162.243.152.217:%s/static/js' % (local_absolute_path, server_absolute_path))
    # local('scp %sstatic/js/jquery-ui.js                     tom@162.243.152.217:%s/static/js' % (local_absolute_path, server_absolute_path))
    # local('scp %sstatic/js/jquery.tablesorter.min.js        tom@162.243.152.217:%s/static/js' % (local_absolute_path, server_absolute_path))
    # local('scp %sstatic/js/jquery.tablesorter.pager.min.js  tom@162.243.152.217:%s/static/js' % (local_absolute_path, server_absolute_path))
    # local('scp %sstatic/js/leaflet.js                       tom@162.243.152.217:%s/static/js' % (local_absolute_path, server_absolute_path))
    # local('scp %sstatic/js/lens.js                          tom@162.243.152.217:%s/static/js' % (local_absolute_path, server_absolute_path))
    # local('scp %sstatic/js/mapbox.uncompressed.js           tom@162.243.152.217:%s/static/js' % (local_absolute_path, server_absolute_path))
    # local('scp %sstatic/js/modernizr.js                     tom@162.243.152.217:%s/static/js' % (local_absolute_path, server_absolute_path))
    # local('scp %sstatic/js/neighborhoods-topo.js            tom@162.243.152.217:%s/static/js' % (local_absolute_path, server_absolute_path))
    # local('scp %sstatic/js/neighborhoods-topo.min.js        tom@162.243.152.217:%s/static/js' % (local_absolute_path, server_absolute_path))
    # local('scp %sstatic/js/sale.js                          tom@162.243.152.217:%s/static/js' % (local_absolute_path, server_absolute_path))
    # local('scp %sstatic/js/search.js                        tom@162.243.152.217:%s/static/js' % (local_absolute_path, server_absolute_path))
    # local('scp %sstatic/js/squares-topo.js                  tom@162.243.152.217:%s/static/js' % (local_absolute_path, server_absolute_path))


